badFlag(automotive_bitcount,'-fschedule-insns').
badFlag(automotive_bitcount,'-fschedule-insns').
badFlag(automotive_bitcount,'-funroll-all-loops').
badFlag(automotive_bitcount,'-funroll-all-loops').
badFlag(automotive_susan_c,'-faggressive-loop-optimizations').
badFlag(automotive_susan_c,'-faggressive-loop-optimizations').
badFlag(automotive_susan_c,'-fbranch-count-reg').
badFlag(automotive_susan_c,'-fbranch-count-reg').
badFlag(automotive_susan_c,'-fcaller-saves').
badFlag(automotive_susan_c,'-fcaller-saves').
badFlag(automotive_susan_c,'-fconserve-stack').
badFlag(automotive_susan_c,'-fconserve-stack').
badFlag(automotive_susan_c,'-fcprop-registers').
badFlag(automotive_susan_c,'-fcprop-registers').
badFlag(automotive_susan_c,'-fcrossjumping').
badFlag(automotive_susan_c,'-fcrossjumping').
badFlag(automotive_susan_c,'-fdce').
badFlag(automotive_susan_c,'-fdce').
badFlag(automotive_susan_c,'-fdelete-null-pointer-checks').
badFlag(automotive_susan_c,'-fdelete-null-pointer-checks').
badFlag(automotive_susan_c,'-fexpensive-optimizations').
badFlag(automotive_susan_c,'-fexpensive-optimizations').
badFlag(automotive_susan_c,'-fforward-propagate').
badFlag(automotive_susan_c,'-fforward-propagate').
badFlag(automotive_susan_c,'-fgcse').
badFlag(automotive_susan_c,'-fgcse').
badFlag(automotive_susan_c,'-fgcse-after-reload').
badFlag(automotive_susan_c,'-fgcse-after-reload').
badFlag(automotive_susan_c,'-fguess-branch-probability').
badFlag(automotive_susan_c,'-fguess-branch-probability').
badFlag(automotive_susan_c,'-fif-conversion').
badFlag(automotive_susan_c,'-fif-conversion').
badFlag(automotive_susan_c,'-fif-conversion2').
badFlag(automotive_susan_c,'-fif-conversion2').
badFlag(automotive_susan_c,'-finline').
badFlag(automotive_susan_c,'-finline').
badFlag(automotive_susan_c,'-finline-functions').
badFlag(automotive_susan_c,'-finline-functions').
badFlag(automotive_susan_c,'-finline-small-functions').
badFlag(automotive_susan_c,'-finline-small-functions').
badFlag(automotive_susan_c,'-fipa-pta').
badFlag(automotive_susan_c,'-fipa-pta').
badFlag(automotive_susan_c,'-fipa-pure-const').
badFlag(automotive_susan_c,'-fipa-pure-const').
badFlag(automotive_susan_c,'-fmerge-constants').
badFlag(automotive_susan_c,'-fmerge-constants').
badFlag(automotive_susan_c,'-fmodulo-sched').
badFlag(automotive_susan_c,'-fmodulo-sched').
badFlag(automotive_susan_c,'-fmove-loop-invariants').
badFlag(automotive_susan_c,'-fmove-loop-invariants').
badFlag(automotive_susan_c,'-fomit-frame-pointer').
badFlag(automotive_susan_c,'-fomit-frame-pointer').
badFlag(automotive_susan_c,'-foptimize-sibling-calls').
badFlag(automotive_susan_c,'-foptimize-sibling-calls').
badFlag(automotive_susan_c,'-fpeephole2').
badFlag(automotive_susan_c,'-fpeephole2').
badFlag(automotive_susan_c,'-frename-registers').
badFlag(automotive_susan_c,'-frename-registers').
badFlag(automotive_susan_c,'-freorder-blocks').
badFlag(automotive_susan_c,'-freorder-blocks').
badFlag(A,'-freorder-functions').
badFlag(automotive_susan_c,'-frerun-cse-after-loop').
badFlag(automotive_susan_c,'-frerun-cse-after-loop').
badFlag(automotive_susan_c,'-freschedule-modulo-scheduled-loops').
badFlag(automotive_susan_c,'-freschedule-modulo-scheduled-loops').
badFlag(automotive_susan_c,'-fsched-interblock').
badFlag(automotive_susan_c,'-fsched-interblock').
badFlag(automotive_susan_c,'-fsched-pressure').
badFlag(automotive_susan_c,'-fsched-pressure').
badFlag(automotive_susan_c,'-fschedule-insns').
badFlag(automotive_susan_c,'-fschedule-insns').
badFlag(automotive_susan_c,'-fschedule-insns2').
badFlag(automotive_susan_c,'-fschedule-insns2').
badFlag(automotive_susan_c,'-fsection-anchors').
badFlag(automotive_susan_c,'-fsection-anchors').
badFlag(automotive_susan_c,'-fsel-sched-pipelining').
badFlag(automotive_susan_c,'-fsel-sched-pipelining').
badFlag(automotive_susan_c,'-fsel-sched-pipelining-outer-loops').
badFlag(automotive_susan_c,'-fsel-sched-pipelining-outer-loops').
badFlag(automotive_susan_c,'-fselective-scheduling').
badFlag(automotive_susan_c,'-fselective-scheduling').
badFlag(automotive_susan_c,'-fselective-scheduling2').
badFlag(automotive_susan_c,'-fselective-scheduling2').
badFlag(automotive_susan_c,'-fshrink-wrap').
badFlag(automotive_susan_c,'-fshrink-wrap').
badFlag(automotive_susan_c,'-fsplit-ivs-in-unroller').
badFlag(automotive_susan_c,'-fsplit-ivs-in-unroller').
badFlag(A,'-fstrict-aliasing').
badFlag(automotive_susan_c,'-ftoplevel-reorder').
badFlag(automotive_susan_c,'-ftoplevel-reorder').
badFlag(automotive_susan_c,'-ftree-bit-ccp').
badFlag(automotive_susan_c,'-ftree-bit-ccp').
badFlag(automotive_susan_c,'-ftree-ccp').
badFlag(automotive_susan_c,'-ftree-ccp').
badFlag(automotive_susan_c,'-ftree-ch').
badFlag(automotive_susan_c,'-ftree-ch').
badFlag(automotive_susan_c,'-ftree-coalesce-vars').
badFlag(automotive_susan_c,'-ftree-coalesce-vars').
badFlag(A,'-ftree-copy-prop').
badFlag(automotive_susan_c,'-ftree-copyrename').
badFlag(automotive_susan_c,'-ftree-copyrename').
badFlag(automotive_susan_c,'-ftree-cselim').
badFlag(automotive_susan_c,'-ftree-cselim').
badFlag(automotive_susan_c,'-ftree-dce').
badFlag(automotive_susan_c,'-ftree-dce').
badFlag(automotive_susan_c,'-ftree-dominator-opts').
badFlag(automotive_susan_c,'-ftree-dominator-opts').
badFlag(automotive_susan_c,'-ftree-forwprop').
badFlag(automotive_susan_c,'-ftree-forwprop').
badFlag(automotive_susan_c,'-ftree-fre').
badFlag(automotive_susan_c,'-ftree-fre').
badFlag(automotive_susan_c,'-ftree-partial-pre').
badFlag(automotive_susan_c,'-ftree-partial-pre').
badFlag(automotive_susan_c,'-ftree-pre').
badFlag(automotive_susan_c,'-ftree-pre').
badFlag(automotive_susan_c,'-ftree-reassoc').
badFlag(automotive_susan_c,'-ftree-reassoc').
badFlag(automotive_susan_c,'-ftree-sink').
badFlag(automotive_susan_c,'-ftree-sink').
badFlag(automotive_susan_c,'-ftree-slsr').
badFlag(automotive_susan_c,'-ftree-slsr').
badFlag(automotive_susan_c,'-ftree-sra').
badFlag(automotive_susan_c,'-ftree-sra').
badFlag(automotive_susan_c,'-ftree-ter').
badFlag(automotive_susan_c,'-ftree-ter').
badFlag(automotive_susan_c,'-ftree-vrp').
badFlag(automotive_susan_c,'-ftree-vrp').
badFlag(automotive_susan_c,'-funroll-all-loops').
badFlag(automotive_susan_c,'-funroll-all-loops').
badFlag(automotive_susan_c,'-funswitch-loops').
badFlag(automotive_susan_c,'-funswitch-loops').
badFlag(automotive_susan_c,'-fvariable-expansion-in-unroller').
badFlag(automotive_susan_c,'-fvariable-expansion-in-unroller').
badFlag(automotive_susan_c,'-fweb').
badFlag(automotive_susan_c,'-fweb').
badFlag(automotive_susan_e,'-fivopts').
badFlag(automotive_susan_e,'-fivopts').
badFlag(A,'-foptimize-sibling-calls') :-
   stmt_code(A,B,C,gimple_call).
badFlag(automotive_susan_s,'-fselective-scheduling').
badFlag(automotive_susan_s,'-fselective-scheduling').
badFlag(automotive_susan_s,'-fselective-scheduling2').
badFlag(automotive_susan_s,'-fselective-scheduling2').
badFlag(automotive_susan_s,'-fvariable-expansion-in-unroller').
badFlag(automotive_susan_s,'-fvariable-expansion-in-unroller').
badFlag(consumer_jpeg_c,'-fcrossjumping').
badFlag(consumer_jpeg_c,'-fcrossjumping').
badFlag(consumer_jpeg_c,'-finline-functions').
badFlag(consumer_jpeg_c,'-finline-functions').
badFlag(consumer_jpeg_c,'-fselective-scheduling').
badFlag(consumer_jpeg_c,'-fselective-scheduling').
badFlag(consumer_jpeg_c,'-ftree-dominator-opts').
badFlag(consumer_jpeg_c,'-ftree-dominator-opts').
badFlag(consumer_jpeg_d,'-faggressive-loop-optimizations').
badFlag(consumer_jpeg_d,'-faggressive-loop-optimizations').
badFlag(consumer_jpeg_d,'-fbranch-count-reg').
badFlag(consumer_jpeg_d,'-fbranch-count-reg').
badFlag(consumer_jpeg_d,'-fcaller-saves').
badFlag(consumer_jpeg_d,'-fcaller-saves').
badFlag(consumer_jpeg_d,'-fconserve-stack').
badFlag(consumer_jpeg_d,'-fconserve-stack').
badFlag(consumer_jpeg_d,'-fcprop-registers').
badFlag(consumer_jpeg_d,'-fcprop-registers').
badFlag(consumer_jpeg_d,'-fcrossjumping').
badFlag(consumer_jpeg_d,'-fcrossjumping').
badFlag(consumer_jpeg_d,'-fcse-follow-jumps').
badFlag(consumer_jpeg_d,'-fcse-follow-jumps').
badFlag(consumer_jpeg_d,'-fdata-sections').
badFlag(consumer_jpeg_d,'-fdata-sections').
badFlag(consumer_jpeg_d,'-fdce').
badFlag(consumer_jpeg_d,'-fdce').
badFlag(consumer_jpeg_d,'-fdelete-null-pointer-checks').
badFlag(consumer_jpeg_d,'-fdelete-null-pointer-checks').
badFlag(consumer_jpeg_d,'-fdse').
badFlag(consumer_jpeg_d,'-fdse').
badFlag(consumer_jpeg_d,'-fearly-inlining').
badFlag(consumer_jpeg_d,'-fearly-inlining').
badFlag(consumer_jpeg_d,'-fexpensive-optimizations').
badFlag(consumer_jpeg_d,'-fexpensive-optimizations').
badFlag(consumer_jpeg_d,'-fforward-propagate').
badFlag(consumer_jpeg_d,'-fforward-propagate').
badFlag(consumer_jpeg_d,'-fgcse-after-reload').
badFlag(consumer_jpeg_d,'-fgcse-after-reload').
badFlag(consumer_jpeg_d,'-fgcse-sm').
badFlag(consumer_jpeg_d,'-fgcse-sm').
badFlag(consumer_jpeg_d,'-fguess-branch-probability').
badFlag(consumer_jpeg_d,'-fguess-branch-probability').
badFlag(consumer_jpeg_d,'-fif-conversion').
badFlag(consumer_jpeg_d,'-fif-conversion').
badFlag(consumer_jpeg_d,'-fif-conversion2').
badFlag(consumer_jpeg_d,'-fif-conversion2').
badFlag(consumer_jpeg_d,'-finline').
badFlag(consumer_jpeg_d,'-finline').
badFlag(consumer_jpeg_d,'-finline-functions').
badFlag(consumer_jpeg_d,'-finline-functions').
badFlag(consumer_jpeg_d,'-finline-functions-called-once').
badFlag(consumer_jpeg_d,'-finline-functions-called-once').
badFlag(consumer_jpeg_d,'-finline-small-functions').
badFlag(consumer_jpeg_d,'-finline-small-functions').
badFlag(consumer_jpeg_d,'-fipa-cp').
badFlag(consumer_jpeg_d,'-fipa-cp').
badFlag(consumer_jpeg_d,'-fipa-cp-clone').
badFlag(consumer_jpeg_d,'-fipa-cp-clone').
badFlag(consumer_jpeg_d,'-fipa-pta').
badFlag(consumer_jpeg_d,'-fipa-pta').
badFlag(consumer_jpeg_d,'-fipa-pure-const').
badFlag(consumer_jpeg_d,'-fipa-pure-const').
badFlag(consumer_jpeg_d,'-fipa-sra').
badFlag(consumer_jpeg_d,'-fipa-sra').
badFlag(consumer_jpeg_d,'-fivopts').
badFlag(consumer_jpeg_d,'-fivopts').
badFlag(consumer_jpeg_d,'-fmerge-constants').
badFlag(consumer_jpeg_d,'-fmerge-constants').
badFlag(consumer_jpeg_d,'-fmodulo-sched').
badFlag(consumer_jpeg_d,'-fmodulo-sched').
badFlag(consumer_jpeg_d,'-fmove-loop-invariants').
badFlag(consumer_jpeg_d,'-fmove-loop-invariants').
badFlag(consumer_jpeg_d,'-fomit-frame-pointer').
badFlag(consumer_jpeg_d,'-fomit-frame-pointer').
badFlag(consumer_jpeg_d,'-foptimize-sibling-calls').
badFlag(consumer_jpeg_d,'-foptimize-sibling-calls').
badFlag(consumer_jpeg_d,'-fpeephole2').
badFlag(consumer_jpeg_d,'-fpeephole2').
badFlag(consumer_jpeg_d,'-fprefetch-loop-arrays').
badFlag(consumer_jpeg_d,'-fprefetch-loop-arrays').
badFlag(consumer_jpeg_d,'-frename-registers').
badFlag(consumer_jpeg_d,'-frename-registers').
badFlag(consumer_jpeg_d,'-freorder-blocks').
badFlag(consumer_jpeg_d,'-freorder-blocks').
badFlag(consumer_jpeg_d,'-frerun-cse-after-loop').
badFlag(consumer_jpeg_d,'-frerun-cse-after-loop').
badFlag(consumer_jpeg_d,'-freschedule-modulo-scheduled-loops').
badFlag(consumer_jpeg_d,'-freschedule-modulo-scheduled-loops').
badFlag(consumer_jpeg_d,'-fsched-interblock').
badFlag(consumer_jpeg_d,'-fsched-interblock').
badFlag(consumer_jpeg_d,'-fschedule-insns2').
badFlag(consumer_jpeg_d,'-fschedule-insns2').
badFlag(consumer_jpeg_d,'-fsection-anchors').
badFlag(consumer_jpeg_d,'-fsection-anchors').
badFlag(consumer_jpeg_d,'-fsel-sched-pipelining').
badFlag(consumer_jpeg_d,'-fsel-sched-pipelining').
badFlag(consumer_jpeg_d,'-fsel-sched-pipelining-outer-loops').
badFlag(consumer_jpeg_d,'-fsel-sched-pipelining-outer-loops').
badFlag(consumer_jpeg_d,'-fselective-scheduling2').
badFlag(consumer_jpeg_d,'-fselective-scheduling2').
badFlag(consumer_jpeg_d,'-fshrink-wrap').
badFlag(consumer_jpeg_d,'-fshrink-wrap').
badFlag(consumer_jpeg_d,'-fsplit-ivs-in-unroller').
badFlag(consumer_jpeg_d,'-fsplit-ivs-in-unroller').
badFlag(consumer_jpeg_d,'-fthread-jumps').
badFlag(consumer_jpeg_d,'-fthread-jumps').
badFlag(consumer_jpeg_d,'-ftoplevel-reorder').
badFlag(consumer_jpeg_d,'-ftoplevel-reorder').
badFlag(consumer_jpeg_d,'-ftree-bit-ccp').
badFlag(consumer_jpeg_d,'-ftree-bit-ccp').
badFlag(consumer_jpeg_d,'-ftree-ccp').
badFlag(consumer_jpeg_d,'-ftree-ccp').
badFlag(consumer_jpeg_d,'-ftree-ch').
badFlag(consumer_jpeg_d,'-ftree-ch').
badFlag(consumer_jpeg_d,'-ftree-coalesce-vars').
badFlag(consumer_jpeg_d,'-ftree-coalesce-vars').
badFlag(consumer_jpeg_d,'-ftree-copyrename').
badFlag(consumer_jpeg_d,'-ftree-copyrename').
badFlag(consumer_jpeg_d,'-ftree-dce').
badFlag(consumer_jpeg_d,'-ftree-dce').
badFlag(consumer_jpeg_d,'-ftree-dominator-opts').
badFlag(consumer_jpeg_d,'-ftree-dominator-opts').
badFlag(consumer_jpeg_d,'-ftree-forwprop').
badFlag(consumer_jpeg_d,'-ftree-forwprop').
badFlag(consumer_jpeg_d,'-ftree-fre').
badFlag(consumer_jpeg_d,'-ftree-fre').
badFlag(consumer_jpeg_d,'-ftree-loop-distribute-patterns').
badFlag(consumer_jpeg_d,'-ftree-loop-distribute-patterns').
badFlag(A,'-ftree-loop-if-convert').
badFlag(consumer_jpeg_d,'-ftree-loop-im').
badFlag(consumer_jpeg_d,'-ftree-loop-im').
badFlag(consumer_jpeg_d,'-ftree-loop-ivcanon').
badFlag(consumer_jpeg_d,'-ftree-loop-ivcanon').
badFlag(consumer_jpeg_d,'-ftree-loop-optimize').
badFlag(consumer_jpeg_d,'-ftree-loop-optimize').
badFlag(consumer_jpeg_d,'-ftree-partial-pre').
badFlag(consumer_jpeg_d,'-ftree-partial-pre').
badFlag(consumer_jpeg_d,'-ftree-pre').
badFlag(consumer_jpeg_d,'-ftree-pre').
badFlag(consumer_jpeg_d,'-ftree-pta').
badFlag(consumer_jpeg_d,'-ftree-pta').
badFlag(consumer_jpeg_d,'-ftree-reassoc').
badFlag(consumer_jpeg_d,'-ftree-reassoc').
badFlag(consumer_jpeg_d,'-ftree-scev-cprop').
badFlag(consumer_jpeg_d,'-ftree-scev-cprop').
badFlag(consumer_jpeg_d,'-ftree-sink').
badFlag(consumer_jpeg_d,'-ftree-sink').
badFlag(consumer_jpeg_d,'-ftree-slsr').
badFlag(consumer_jpeg_d,'-ftree-slsr').
badFlag(consumer_jpeg_d,'-ftree-sra').
badFlag(consumer_jpeg_d,'-ftree-sra').
badFlag(consumer_jpeg_d,'-ftree-tail-merge').
badFlag(consumer_jpeg_d,'-ftree-tail-merge').
badFlag(consumer_jpeg_d,'-ftree-ter').
badFlag(consumer_jpeg_d,'-ftree-ter').
badFlag(consumer_jpeg_d,'-ftree-vectorize').
badFlag(consumer_jpeg_d,'-ftree-vectorize').
badFlag(consumer_jpeg_d,'-ftree-vrp').
badFlag(consumer_jpeg_d,'-ftree-vrp').
badFlag(consumer_jpeg_d,'-funroll-all-loops').
badFlag(consumer_jpeg_d,'-funroll-all-loops').
badFlag(consumer_jpeg_d,'-funswitch-loops').
badFlag(consumer_jpeg_d,'-funswitch-loops').
badFlag(consumer_jpeg_d,'-fvariable-expansion-in-unroller').
badFlag(consumer_jpeg_d,'-fvariable-expansion-in-unroller').
badFlag(consumer_jpeg_d,'-fvect-cost-model').
badFlag(consumer_jpeg_d,'-fvect-cost-model').
badFlag(consumer_tiff2rgba,'-faggressive-loop-optimizations').
badFlag(consumer_tiff2rgba,'-faggressive-loop-optimizations').
badFlag(consumer_tiff2rgba,'-fbranch-count-reg').
badFlag(consumer_tiff2rgba,'-fbranch-count-reg').
badFlag(consumer_tiff2rgba,'-fconserve-stack').
badFlag(consumer_tiff2rgba,'-fconserve-stack').
badFlag(consumer_tiff2rgba,'-fcrossjumping').
badFlag(consumer_tiff2rgba,'-fcrossjumping').
badFlag(consumer_tiff2rgba,'-fcse-follow-jumps').
badFlag(consumer_tiff2rgba,'-fcse-follow-jumps').
badFlag(consumer_tiff2rgba,'-fdata-sections').
badFlag(consumer_tiff2rgba,'-fdata-sections').
badFlag(consumer_tiff2rgba,'-fdelete-null-pointer-checks').
badFlag(consumer_tiff2rgba,'-fdelete-null-pointer-checks').
badFlag(consumer_tiff2rgba,'-fdse').
badFlag(consumer_tiff2rgba,'-fdse').
badFlag(consumer_tiff2rgba,'-fearly-inlining').
badFlag(consumer_tiff2rgba,'-fearly-inlining').
badFlag(consumer_tiff2rgba,'-fexpensive-optimizations').
badFlag(consumer_tiff2rgba,'-fexpensive-optimizations').
badFlag(consumer_tiff2rgba,'-fforward-propagate').
badFlag(consumer_tiff2rgba,'-fforward-propagate').
badFlag(consumer_tiff2rgba,'-fgcse-after-reload').
badFlag(consumer_tiff2rgba,'-fgcse-after-reload').
badFlag(consumer_tiff2rgba,'-fgcse-sm').
badFlag(consumer_tiff2rgba,'-fgcse-sm').
badFlag(consumer_tiff2rgba,'-fguess-branch-probability').
badFlag(consumer_tiff2rgba,'-fguess-branch-probability').
badFlag(consumer_tiff2rgba,'-fif-conversion').
badFlag(consumer_tiff2rgba,'-fif-conversion').
badFlag(consumer_tiff2rgba,'-fif-conversion2').
badFlag(consumer_tiff2rgba,'-fif-conversion2').
badFlag(consumer_tiff2rgba,'-finline').
badFlag(consumer_tiff2rgba,'-finline').
badFlag(consumer_tiff2rgba,'-finline-functions').
badFlag(consumer_tiff2rgba,'-finline-functions').
badFlag(consumer_tiff2rgba,'-finline-functions-called-once').
badFlag(consumer_tiff2rgba,'-finline-functions-called-once').
badFlag(consumer_tiff2rgba,'-finline-small-functions').
badFlag(consumer_tiff2rgba,'-finline-small-functions').
badFlag(consumer_tiff2rgba,'-fipa-cp').
badFlag(consumer_tiff2rgba,'-fipa-cp').
badFlag(consumer_tiff2rgba,'-fipa-cp-clone').
badFlag(consumer_tiff2rgba,'-fipa-cp-clone').
badFlag(consumer_tiff2rgba,'-fipa-pta').
badFlag(consumer_tiff2rgba,'-fipa-pta').
badFlag(consumer_tiff2rgba,'-fipa-sra').
badFlag(consumer_tiff2rgba,'-fipa-sra').
badFlag(consumer_tiff2rgba,'-fivopts').
badFlag(consumer_tiff2rgba,'-fivopts').
badFlag(consumer_tiff2rgba,'-fmerge-constants').
badFlag(consumer_tiff2rgba,'-fmerge-constants').
badFlag(consumer_tiff2rgba,'-fmodulo-sched').
badFlag(consumer_tiff2rgba,'-fmodulo-sched').
badFlag(consumer_tiff2rgba,'-fmove-loop-invariants').
badFlag(consumer_tiff2rgba,'-fmove-loop-invariants').
badFlag(consumer_tiff2rgba,'-fomit-frame-pointer').
badFlag(consumer_tiff2rgba,'-fomit-frame-pointer').
badFlag(consumer_tiff2rgba,'-fpeephole2').
badFlag(consumer_tiff2rgba,'-fpeephole2').
badFlag(A,'-fpredictive-commoning') :-
   edge_flag(A,B,C,dfs_back).
badFlag(consumer_tiff2rgba,'-fprefetch-loop-arrays').
badFlag(consumer_tiff2rgba,'-fprefetch-loop-arrays').
badFlag(consumer_tiff2rgba,'-freorder-blocks').
badFlag(consumer_tiff2rgba,'-freorder-blocks').
badFlag(consumer_tiff2rgba,'-frerun-cse-after-loop').
badFlag(consumer_tiff2rgba,'-frerun-cse-after-loop').
badFlag(consumer_tiff2rgba,'-freschedule-modulo-scheduled-loops').
badFlag(consumer_tiff2rgba,'-freschedule-modulo-scheduled-loops').
badFlag(consumer_tiff2rgba,'-fsched-pressure').
badFlag(consumer_tiff2rgba,'-fsched-pressure').
badFlag(consumer_tiff2rgba,'-fschedule-insns').
badFlag(consumer_tiff2rgba,'-fschedule-insns').
badFlag(consumer_tiff2rgba,'-fschedule-insns2').
badFlag(consumer_tiff2rgba,'-fschedule-insns2').
badFlag(consumer_tiff2rgba,'-fsection-anchors').
badFlag(consumer_tiff2rgba,'-fsection-anchors').
badFlag(consumer_tiff2rgba,'-fselective-scheduling').
badFlag(consumer_tiff2rgba,'-fselective-scheduling').
badFlag(consumer_tiff2rgba,'-fselective-scheduling2').
badFlag(consumer_tiff2rgba,'-fselective-scheduling2').
badFlag(consumer_tiff2rgba,'-fshrink-wrap').
badFlag(consumer_tiff2rgba,'-fshrink-wrap').
badFlag(consumer_tiff2rgba,'-fsplit-ivs-in-unroller').
badFlag(consumer_tiff2rgba,'-fsplit-ivs-in-unroller').
badFlag(consumer_tiff2rgba,'-fthread-jumps').
badFlag(consumer_tiff2rgba,'-fthread-jumps').
badFlag(A,'-ftoplevel-reorder') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,true).
badFlag(consumer_tiff2rgba,'-ftree-ccp').
badFlag(consumer_tiff2rgba,'-ftree-ccp').
badFlag(consumer_tiff2rgba,'-ftree-ch').
badFlag(consumer_tiff2rgba,'-ftree-ch').
badFlag(consumer_tiff2rgba,'-ftree-coalesce-vars').
badFlag(consumer_tiff2rgba,'-ftree-coalesce-vars').
badFlag(consumer_tiff2rgba,'-ftree-copyrename').
badFlag(consumer_tiff2rgba,'-ftree-copyrename').
badFlag(consumer_tiff2rgba,'-ftree-cselim').
badFlag(consumer_tiff2rgba,'-ftree-cselim').
badFlag(consumer_tiff2rgba,'-ftree-dce').
badFlag(consumer_tiff2rgba,'-ftree-dce').
badFlag(A,'-ftree-dominator-opts') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,true).
badFlag(consumer_tiff2rgba,'-ftree-forwprop').
badFlag(consumer_tiff2rgba,'-ftree-forwprop').
badFlag(A,'-ftree-fre') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,true).
badFlag(consumer_tiff2rgba,'-ftree-loop-distribute-patterns').
badFlag(consumer_tiff2rgba,'-ftree-loop-distribute-patterns').
badFlag(consumer_tiff2rgba,'-ftree-loop-im').
badFlag(consumer_tiff2rgba,'-ftree-loop-im').
badFlag(consumer_tiff2rgba,'-ftree-loop-ivcanon').
badFlag(consumer_tiff2rgba,'-ftree-loop-ivcanon').
badFlag(consumer_tiff2rgba,'-ftree-loop-optimize').
badFlag(consumer_tiff2rgba,'-ftree-loop-optimize').
badFlag(consumer_tiff2rgba,'-ftree-partial-pre').
badFlag(consumer_tiff2rgba,'-ftree-partial-pre').
badFlag(consumer_tiff2rgba,'-ftree-pre').
badFlag(consumer_tiff2rgba,'-ftree-pre').
badFlag(consumer_tiff2rgba,'-ftree-pta').
badFlag(consumer_tiff2rgba,'-ftree-pta').
badFlag(consumer_tiff2rgba,'-ftree-reassoc').
badFlag(consumer_tiff2rgba,'-ftree-reassoc').
badFlag(consumer_tiff2rgba,'-ftree-scev-cprop').
badFlag(consumer_tiff2rgba,'-ftree-scev-cprop').
badFlag(consumer_tiff2rgba,'-ftree-sink').
badFlag(consumer_tiff2rgba,'-ftree-sink').
badFlag(consumer_tiff2rgba,'-ftree-slp-vectorize').
badFlag(consumer_tiff2rgba,'-ftree-slp-vectorize').
badFlag(consumer_tiff2rgba,'-ftree-slsr').
badFlag(consumer_tiff2rgba,'-ftree-slsr').
badFlag(consumer_tiff2rgba,'-ftree-switch-conversion').
badFlag(consumer_tiff2rgba,'-ftree-switch-conversion').
badFlag(consumer_tiff2rgba,'-ftree-tail-merge').
badFlag(consumer_tiff2rgba,'-ftree-tail-merge').
badFlag(consumer_tiff2rgba,'-ftree-ter').
badFlag(consumer_tiff2rgba,'-ftree-ter').
badFlag(consumer_tiff2rgba,'-ftree-vectorize').
badFlag(consumer_tiff2rgba,'-ftree-vectorize').
badFlag(consumer_tiff2rgba,'-ftree-vrp').
badFlag(consumer_tiff2rgba,'-ftree-vrp').
badFlag(A,'-funroll-all-loops') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,true).
badFlag(consumer_tiff2rgba,'-funswitch-loops').
badFlag(consumer_tiff2rgba,'-funswitch-loops').
badFlag(consumer_tiff2rgba,'-fvect-cost-model').
badFlag(consumer_tiff2rgba,'-fvect-cost-model').
badFlag(consumer_tiff2rgba,'-fweb').
badFlag(consumer_tiff2rgba,'-fweb').
badFlag(consumer_tiffdither,'-fmodulo-sched').
badFlag(consumer_tiffdither,'-fmodulo-sched').
badFlag(consumer_tiffdither,'-fsched-interblock').
badFlag(consumer_tiffdither,'-fsched-interblock').
badFlag(consumer_tiffdither,'-funroll-all-loops').
badFlag(consumer_tiffdither,'-funroll-all-loops').
badFlag(consumer_tiffmedian,'-faggressive-loop-optimizations').
badFlag(consumer_tiffmedian,'-faggressive-loop-optimizations').
badFlag(consumer_tiffmedian,'-fbranch-count-reg').
badFlag(consumer_tiffmedian,'-fbranch-count-reg').
badFlag(consumer_tiffmedian,'-fcrossjumping').
badFlag(consumer_tiffmedian,'-fcrossjumping').
badFlag(consumer_tiffmedian,'-fcse-follow-jumps').
badFlag(consumer_tiffmedian,'-fcse-follow-jumps').
badFlag(consumer_tiffmedian,'-fdce').
badFlag(consumer_tiffmedian,'-fdce').
badFlag(consumer_tiffmedian,'-fdelete-null-pointer-checks').
badFlag(consumer_tiffmedian,'-fdelete-null-pointer-checks').
badFlag(consumer_tiffmedian,'-fexpensive-optimizations').
badFlag(consumer_tiffmedian,'-fexpensive-optimizations').
badFlag(consumer_tiffmedian,'-fforward-propagate').
badFlag(consumer_tiffmedian,'-fforward-propagate').
badFlag(consumer_tiffmedian,'-fgcse-after-reload').
badFlag(consumer_tiffmedian,'-fgcse-after-reload').
badFlag(consumer_tiffmedian,'-fgcse-las').
badFlag(consumer_tiffmedian,'-fgcse-las').
badFlag(consumer_tiffmedian,'-fif-conversion').
badFlag(consumer_tiffmedian,'-fif-conversion').
badFlag(consumer_tiffmedian,'-fif-conversion2').
badFlag(consumer_tiffmedian,'-fif-conversion2').
badFlag(consumer_tiffmedian,'-finline').
badFlag(consumer_tiffmedian,'-finline').
badFlag(consumer_tiffmedian,'-finline-functions').
badFlag(consumer_tiffmedian,'-finline-functions').
badFlag(consumer_tiffmedian,'-finline-small-functions').
badFlag(consumer_tiffmedian,'-finline-small-functions').
badFlag(consumer_tiffmedian,'-fipa-cp').
badFlag(consumer_tiffmedian,'-fipa-cp').
badFlag(consumer_tiffmedian,'-fipa-pta').
badFlag(consumer_tiffmedian,'-fipa-pta').
badFlag(consumer_tiffmedian,'-fipa-pure-const').
badFlag(consumer_tiffmedian,'-fipa-pure-const').
badFlag(consumer_tiffmedian,'-fipa-sra').
badFlag(consumer_tiffmedian,'-fipa-sra').
badFlag(consumer_tiffmedian,'-fivopts').
badFlag(consumer_tiffmedian,'-fivopts').
badFlag(consumer_tiffmedian,'-fmerge-constants').
badFlag(consumer_tiffmedian,'-fmerge-constants').
badFlag(consumer_tiffmedian,'-fmodulo-sched').
badFlag(consumer_tiffmedian,'-fmodulo-sched').
badFlag(consumer_tiffmedian,'-fmove-loop-invariants').
badFlag(consumer_tiffmedian,'-fmove-loop-invariants').
badFlag(consumer_tiffmedian,'-fpeephole2').
badFlag(consumer_tiffmedian,'-fpeephole2').
badFlag(consumer_tiffmedian,'-frename-registers').
badFlag(consumer_tiffmedian,'-frename-registers').
badFlag(consumer_tiffmedian,'-frerun-cse-after-loop').
badFlag(consumer_tiffmedian,'-frerun-cse-after-loop').
badFlag(consumer_tiffmedian,'-freschedule-modulo-scheduled-loops').
badFlag(consumer_tiffmedian,'-freschedule-modulo-scheduled-loops').
badFlag(consumer_tiffmedian,'-fschedule-insns2').
badFlag(consumer_tiffmedian,'-fschedule-insns2').
badFlag(consumer_tiffmedian,'-fselective-scheduling').
badFlag(consumer_tiffmedian,'-fselective-scheduling').
badFlag(consumer_tiffmedian,'-fselective-scheduling2').
badFlag(consumer_tiffmedian,'-fselective-scheduling2').
badFlag(consumer_tiffmedian,'-ftree-ccp').
badFlag(consumer_tiffmedian,'-ftree-ccp').
badFlag(consumer_tiffmedian,'-ftree-coalesce-vars').
badFlag(consumer_tiffmedian,'-ftree-coalesce-vars').
badFlag(consumer_tiffmedian,'-ftree-copyrename').
badFlag(consumer_tiffmedian,'-ftree-copyrename').
badFlag(consumer_tiffmedian,'-ftree-cselim').
badFlag(consumer_tiffmedian,'-ftree-cselim').
badFlag(consumer_tiffmedian,'-ftree-dominator-opts').
badFlag(consumer_tiffmedian,'-ftree-dominator-opts').
badFlag(consumer_tiffmedian,'-ftree-forwprop').
badFlag(consumer_tiffmedian,'-ftree-forwprop').
badFlag(consumer_tiffmedian,'-ftree-fre').
badFlag(consumer_tiffmedian,'-ftree-fre').
badFlag(consumer_tiffmedian,'-ftree-loop-distribute-patterns').
badFlag(consumer_tiffmedian,'-ftree-loop-distribute-patterns').
badFlag(consumer_tiffmedian,'-ftree-loop-im').
badFlag(consumer_tiffmedian,'-ftree-loop-im').
badFlag(consumer_tiffmedian,'-ftree-loop-ivcanon').
badFlag(consumer_tiffmedian,'-ftree-loop-ivcanon').
badFlag(consumer_tiffmedian,'-ftree-partial-pre').
badFlag(consumer_tiffmedian,'-ftree-partial-pre').
badFlag(consumer_tiffmedian,'-ftree-pre').
badFlag(consumer_tiffmedian,'-ftree-pre').
badFlag(consumer_tiffmedian,'-ftree-reassoc').
badFlag(consumer_tiffmedian,'-ftree-reassoc').
badFlag(consumer_tiffmedian,'-ftree-scev-cprop').
badFlag(consumer_tiffmedian,'-ftree-scev-cprop').
badFlag(consumer_tiffmedian,'-ftree-sink').
badFlag(consumer_tiffmedian,'-ftree-sink').
badFlag(consumer_tiffmedian,'-ftree-slp-vectorize').
badFlag(consumer_tiffmedian,'-ftree-slp-vectorize').
badFlag(consumer_tiffmedian,'-ftree-ter').
badFlag(consumer_tiffmedian,'-ftree-ter').
badFlag(consumer_tiffmedian,'-ftree-vectorize').
badFlag(consumer_tiffmedian,'-ftree-vectorize').
badFlag(consumer_tiffmedian,'-ftree-vrp').
badFlag(consumer_tiffmedian,'-ftree-vrp').
badFlag(consumer_tiffmedian,'-funroll-all-loops').
badFlag(consumer_tiffmedian,'-funroll-all-loops').
badFlag(consumer_tiffmedian,'-fvariable-expansion-in-unroller').
badFlag(consumer_tiffmedian,'-fvariable-expansion-in-unroller').
badFlag(consumer_tiffmedian,'-fvect-cost-model').
badFlag(consumer_tiffmedian,'-fvect-cost-model').
badFlag(network_dijkstra,'-fbranch-count-reg').
badFlag(network_dijkstra,'-fbranch-count-reg').
badFlag(A,'-fcaller-saves') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-fcprop-registers') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-fcrossjumping') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-fcse-follow-jumps') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fdata-sections').
badFlag(network_dijkstra,'-fdata-sections').
badFlag(network_dijkstra,'-fdce').
badFlag(network_dijkstra,'-fdce').
badFlag(network_dijkstra,'-fexpensive-optimizations').
badFlag(network_dijkstra,'-fexpensive-optimizations').
badFlag(A,'-fforward-propagate') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fgcse').
badFlag(network_dijkstra,'-fgcse').
badFlag(A,'-fgcse-after-reload') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fguess-branch-probability').
badFlag(network_dijkstra,'-fguess-branch-probability').
badFlag(network_dijkstra,'-fif-conversion2').
badFlag(network_dijkstra,'-fif-conversion2').
badFlag(network_dijkstra,'-finline-small-functions').
badFlag(network_dijkstra,'-finline-small-functions').
badFlag(network_dijkstra,'-fivopts').
badFlag(network_dijkstra,'-fivopts').
badFlag(A,'-fmerge-constants') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fmodulo-sched').
badFlag(network_dijkstra,'-fmodulo-sched').
badFlag(A,'-fmove-loop-invariants') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fomit-frame-pointer').
badFlag(network_dijkstra,'-fomit-frame-pointer').
badFlag(A,'-frename-registers') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-freorder-blocks').
badFlag(network_dijkstra,'-freorder-blocks').
badFlag(network_dijkstra,'-frerun-cse-after-loop').
badFlag(network_dijkstra,'-frerun-cse-after-loop').
badFlag(network_dijkstra,'-freschedule-modulo-scheduled-loops').
badFlag(network_dijkstra,'-freschedule-modulo-scheduled-loops').
badFlag(A,'-fsched-interblock') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-fsched-pressure') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fschedule-insns').
badFlag(network_dijkstra,'-fschedule-insns').
badFlag(network_dijkstra,'-fschedule-insns2').
badFlag(network_dijkstra,'-fschedule-insns2').
badFlag(network_dijkstra,'-fsection-anchors').
badFlag(network_dijkstra,'-fsection-anchors').
badFlag(A,'-fsel-sched-pipelining') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fsel-sched-pipelining-outer-loops').
badFlag(network_dijkstra,'-fsel-sched-pipelining-outer-loops').
badFlag(network_dijkstra,'-fselective-scheduling').
badFlag(network_dijkstra,'-fselective-scheduling').
badFlag(A,'-fselective-scheduling2') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fshrink-wrap').
badFlag(network_dijkstra,'-fshrink-wrap').
badFlag(network_dijkstra,'-fsplit-ivs-in-unroller').
badFlag(network_dijkstra,'-fsplit-ivs-in-unroller').
badFlag(A,'-ftoplevel-reorder') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-ftree-ch').
badFlag(network_dijkstra,'-ftree-ch').
badFlag(A,'-ftree-dce') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-ftree-dominator-opts') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-ftree-fre') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-ftree-loop-im') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-ftree-loop-optimize').
badFlag(network_dijkstra,'-ftree-loop-optimize').
badFlag(network_dijkstra,'-ftree-partial-pre').
badFlag(network_dijkstra,'-ftree-partial-pre').
badFlag(A,'-ftree-pre') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-ftree-scev-cprop').
badFlag(network_dijkstra,'-ftree-scev-cprop').
badFlag(network_dijkstra,'-ftree-tail-merge').
badFlag(network_dijkstra,'-ftree-tail-merge').
badFlag(network_dijkstra,'-ftree-ter').
badFlag(network_dijkstra,'-ftree-ter').
badFlag(network_dijkstra,'-ftree-vectorize').
badFlag(network_dijkstra,'-ftree-vectorize').
badFlag(A,'-ftree-vrp') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-funroll-all-loops') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(A,'-fvect-cost-model') :-
   edge_flag(A,B,C,dfs_back), edge_flag(A,B,C,false).
badFlag(network_dijkstra,'-fweb').
badFlag(network_dijkstra,'-fweb').
badFlag(security_rijndael_d,'-fschedule-insns').
badFlag(security_rijndael_d,'-fschedule-insns').
badFlag(security_rijndael_d,'-ftree-copyrename').
badFlag(security_rijndael_d,'-ftree-copyrename').
badFlag(security_rijndael_d,'-ftree-tail-merge').
badFlag(security_rijndael_d,'-ftree-tail-merge').
badFlag(security_rijndael_e,'-ftree-reassoc').
badFlag(security_rijndael_e,'-ftree-reassoc').
badFlag(security_rijndael_e,'-ftree-sink').
badFlag(security_rijndael_e,'-ftree-sink').
badFlag(security_sha,'-fgcse').
badFlag(security_sha,'-fgcse').
badFlag(security_sha,'-ftree-vectorize').
badFlag(security_sha,'-ftree-vectorize').
badFlag(telecom_adpcm_c,'-fmove-loop-invariants').
badFlag(telecom_adpcm_c,'-fmove-loop-invariants').
badFlag(telecom_adpcm_c,'-fsel-sched-pipelining').
badFlag(telecom_adpcm_c,'-fsel-sched-pipelining').
badFlag(telecom_adpcm_c,'-ftree-partial-pre').
badFlag(telecom_adpcm_c,'-ftree-partial-pre').
badFlag(telecom_adpcm_d,'-fmove-loop-invariants').
badFlag(telecom_adpcm_d,'-fmove-loop-invariants').
badFlag(telecom_adpcm_d,'-fselective-scheduling2').
badFlag(telecom_adpcm_d,'-fselective-scheduling2').
badFlag(telecom_adpcm_d,'-ftree-forwprop').
badFlag(telecom_adpcm_d,'-ftree-forwprop').
badFlag(telecom_adpcm_d,'-ftree-vrp').
badFlag(telecom_adpcm_d,'-ftree-vrp').
badFlag(telecom_CRC32,'-fsched-interblock').
badFlag(telecom_CRC32,'-fsched-interblock').
